version: "1.0"
type: route
data:
  url: "/services/clamav/settings"
  title: _("Settings")
  notificationTitle: gettext('Updated Antivirus settings.')
  component: omv-services-clamav-settings-form-page
